language: python
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - pip install coverage
    - pip install codecov
# command to run tests

install:


script: 
    - coverage  run  --omit 'vinlookup/tests/*.*' -m py.test

notifications:
  email: false

after_success:
  - codecov
